### ISSUE TITLE
Could not find error_to recipient

### ISSUE THREAD

**Issue by dougdever** [ampledata/hambot#1]
My attempt to run the bot keeps dumping out with a ValueError: Could not find errors_to recipient.  Noticied in constants.py it was defined as you.  Changed to my slack profile and still no joy.

**Comment by dougdever** [comment]
Traceback (most recent call last):
  File "/home/doug/.local/bin/hambot", line 11, in <module>
    sys.exit(cli())
  File "/home/doug/.local/lib/python2.7/site-packages/hambot/cmd.py", line 45, in cli
    bot = slackbot.bot.Bot()
  File "/home/doug/.local/lib/python2.7/site-packages/slackbot/bot.py", line 29, in __init__
    settings.ERRORS_TO)
  File "/home/doug/.local/lib/python2.7/site-packages/slackbot/dispatcher.py", line 29, in __init__
    errors_to))
ValueError: Could not find errors_to recipient 'ab8m'

**Comment by dougdever** [comment]
Pointed it to a channel name instead of as a DM and it works
